name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    env:
      VITE_RAPIDAPI_KEY: ${{ secrets.VITE_RAPIDAPI_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify API Key
        run: |
          if [ -z "$VITE_RAPIDAPI_KEY" ]; then
            echo "::error::VITE_RAPIDAPI_KEY is not set. Please add it to repository secrets."
            exit 1
          else
            echo "VITE_RAPIDAPI_KEY is properly set"
          fi

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          cache: npm

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        env:
          BASE_PATH: '/FlexForEx'
        run: pnpm run build

      - name: Debug Environment
        run: |
          echo "VITE_RAPIDAPI_KEY exists: ${{ env.VITE_RAPIDAPI_KEY != '' }}"
          echo "Build directory contents:"
          ls -la build/

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      actions: read
      contents: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
