name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  pages: write
  id-token: write
  actions: read
  contents: read

jobs:
  build_site:
    runs-on: ubuntu-latest
    env:
      VITE_RAPIDAPI_KEY: ${{ secrets.VITE_RAPIDAPI_KEY }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          VITE_RAPIDAPI_KEY: ${{ secrets.VITE_RAPIDAPI_KEY }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          cache: npm

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        env:
          BASE_PATH: '/FlexForEx'
        run: pnpm run build

      - name: Debug Environment
        run: |
          echo "VITE_RAPIDAPI_KEY exists: ${{ secrets.VITE_RAPIDAPI_KEY != '' }}"
          echo "Build directory contents:"
          ls -la build/

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      actions: read
      contents: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
