name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tell me a secret!
        run: echo "This is a secret step!"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          cache: npm

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        env:
          BASE_PATH: '/FlexForEx'
        run: pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
          name: 'github-pages' # Explicitly set the artifact name

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
      actions: read
      contents: read

    environment:
      name: FlexForEx
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact-name: 'github-pages' # Ensure this matches the artifact name
